"""update user model

Revision ID: 0e60ac6ddce2
Revises: 96af5110d547
Create Date: 2026-08-11 22:50:42.390741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e60ac6ddce2'
down_revision: Union[str, Sequence[str], None] = '96af5110d547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('course', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'year')
    op.drop_column('users', 'course')
    op.drop_column('users', 'college')
    # ### end Alembic commands ###
