"""add hackathon to teams

Revision ID: 57f660f91ba9
Revises: 2fd9a902e312
Create Date: 2026-08-15 15:16:55.159377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f660f91ba9'
down_revision: Union[str, Sequence[str], None] = '2fd9a902e312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('hackathon_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'hackathons', ['hackathon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'hackathon_id')
    # ### end Alembic commands ###
