"""add profile fields to users

Revision ID: 8281becfc495
Revises: 36d6661e36c0
Create Date: 2026-08-15 13:05:26.736004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8281becfc495'
down_revision: Union[str, Sequence[str], None] = '36d6661e36c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_roles')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
