"""add proctoring sessions

Revision ID: 84008e27ad59
Revises: df82e4c2c1f9
Create Date: 2026-09-30 13:49:27.698696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84008e27ad59'
down_revision: Union[str, Sequence[str], None] = 'df82e4c2c1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctoring_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctoring_sessions_active'), 'proctoring_sessions', ['active'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_hackathon_id'), 'proctoring_sessions', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_participant_id'), 'proctoring_sessions', ['participant_id'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_user_id'), 'proctoring_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proctoring_sessions_user_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_participant_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_hackathon_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_active'), table_name='proctoring_sessions')
    op.drop_table('proctoring_sessions')
    # ### end Alembic commands ###
