"""add team to participants

Revision ID: c61f5a0ad00b
Revises: 873e9541695a
Create Date: 2026-08-15 15:40:53.891113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61f5a0ad00b'
down_revision: Union[str, Sequence[str], None] = '873e9541695a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'participants', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.drop_column('participants', 'team_id')
    # ### end Alembic commands ###
