"""add organizer profile fields

Revision ID: c7c776ec6879
Revises: fb59f778a369
Create Date: 2026-08-22 00:05:32.364213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c776ec6879'
down_revision: Union[str, Sequence[str], None] = 'fb59f778a369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=150), nullable=True))
    op.alter_column('users', 'college',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'course',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'course',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('users', 'college',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'designation')
    op.drop_column('users', 'organization')
    # ### end Alembic commands ###
