"""add organizer ownership to hackathons

Revision ID: eb6fb355cea2
Revises: ec4a1eceded7
Create Date: 2026-08-18 22:12:45.026312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6fb355cea2'
down_revision: Union[str, Sequence[str], None] = 'ec4a1eceded7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('organizer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hackathons_organizer_id'), 'hackathons', ['organizer_id'], unique=False)
    op.create_foreign_key(None, 'hackathons', 'users', ['organizer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hackathons', type_='foreignkey')
    op.drop_index(op.f('ix_hackathons_organizer_id'), table_name='hackathons')
    op.drop_column('hackathons', 'organizer_id')
    # ### end Alembic commands ###
